### ISSUE TITLE
Searching for a file sent before the bot was added

### ISSUE THREAD

**Issue by nukeinmw2** [dhrumilp15/discordfs#17]
In this case, a .zip file named "midi.zip" or "midis.zip," sent probably a year or so ago. If there were any way to archive all files sent before the bot was added, this would be great!

**Comment by dhrumilp15** [comment]
First implementation for this in PR #33 !

**Comment by dhrumilp15** [comment]
#38 (Main as of July 17, 2021) should contain a fix for this issue!

Note: Historical files are searched by channel, so you currently have to call the /search command in the channel that contains the files

**Comment by dhrumilp15** [comment]
There have been no bugs raised for #38 and onward! This issue will now be closed, but feel free to reopen the issue if something should be re-explored.

**Comment by dhrumilp15** [comment]
For future reference, the bot now searches in all channels as of #62
